### PR TITLE
Cards left

### PR DESCRIPTION
**Pull request by maysw**

### CODE REVIEW

**Comment by danielgwj** [comment]
I feel the cardsLeft-- is placed at the wrong place, because it doesn't really do the stuff it should do.

Instead, try putting cardsLeft-- at the dealFour function. It would make more sense.

**Comment by maysw** [comment]
But I also need it to remove a card whenever the user removes the card.
Wouldn't placing it in the remove function make more sense because the deal
four function calls the remove function to remove from the deck?

Also, for some reason I am not getting a working version of the game on my
computer. It may be something on my end, but it is kind of a pain and I
need to get this fixed before the next assignment.

**Comment by danielgwj** [comment]
Oh i thought the cards left was meant to show the cards left in the deck? and not the cards left for the user to remove? 

Sorry noticed this abit too late. weirdly i didnt see your reply an hour ago! Sorry!

**Comment by maysw** [comment]
Dang, that is true, I don't know why I didn't think of that earlier. I'll
change it now. Can you verify the pull request for me?

**Pull request merged**
