### PR TITLE
New Game Button

### PR DESCRIPTION
**Pull request by danielgwj**
Added New game button and it is working.

Noticed that I might have a liability issue with CardsLeft and Score functions.

### CODE REVIEW

**Comment by maysw** [comment]
Looks good dude

**Comment by matsuish** [comment]
The new game button does not work on my computer...
am I missing something?

**Comment by maysw** [comment]
Yeah, I can't get a working copy on my computer. Are we sure the repo has
the correct version of the game?

**Comment by matsuish** [comment]
It worked when I changed browser.

**Pull request merged**
