### PR TITLE
English game

### PR DESCRIPTION
**Pull request by matsuish**
I am trying if I can pass travisCI
modified application controller tests

changes:
created EnglishGame class
modified routes and application controller
add links to the other language game

### CODE REVIEW

**Comment by matsuish** [comment]
Seems finally I could pass travisCI.

I have to apologize that before this pull request, I happened to commit my changes to the master, so the master is already updated. I am sorry for that.

what I have done is below:

1.added EnglishGame class.
2.modified routes.class and applicationcontroller.class. basically renaming "Game" or "AcesUp" to "EnglishGame" or "EnglishAcesUp"
3.renamed AcesUp.flt.html to EnglishAcesUp.flt.html, and modified related things (like link in index page)
4.Added links to the other language game in each game page. I will erace this if it's unnecessary.

**Comment by danielgwj** [comment]
its fine dont worry!
One thing I noticed on the previous commit is that in your application controller, in the gameResetEnglish() you built the deck twice, might want to check that out and change it along with this pull request

**Comment by matsuish** [comment]
Oh, I missed it.
Thanks! I fixed it.

**Comment by danielgwj** [comment]
Alright I just tested it and everything looks good!
Our coverage reached 100% so good job guys!

**Comment by danielgwj** [comment]
Coverage was 100% so good job!

**Pull request merged**
